DROP TABLE IF EXISTS ISPUNJENI_UPITNICI;
DROP TABLE IF EXISTS UPITNIK CASCADE;
DROP TABLE IF EXISTS POTRES;
DROP TABLE IF EXISTS MJESTO;
DROP TABLE IF EXISTS SEIZMOLOG;
DROP TABLE IF EXISTS ODGOVOR CASCADE;
DROP TABLE IF EXISTS PITANJE CASCADE;

CREATE TABLE PITANJE
(
  idPitanje INT NOT NULL,
  tekstPitanje VARCHAR NOT NULL,
  PRIMARY KEY (idPitanje)
);

CREATE TABLE ODGOVOR
(
  idOdgovor INT NOT NULL,
  idPitanje INT NOT NULL,
  tekstOdgovor VARCHAR NOT NULL,
  intenzitetOdgovor NUMERIC NOT NULL,
  PRIMARY KEY (idOdgovor),
  FOREIGN KEY (idPitanje) REFERENCES PITANJE(idPitanje) ON DELETE CASCADE
);

CREATE TABLE SEIZMOLOG
(
  ime VARCHAR,
  prezime VARCHAR,
  email VARCHAR NOT NULL,
  lozinka VARCHAR NOT NULL,
  uloga VARCHAR NOT NULL CHECK (uloga IN('admin', 'znanstvenik')),
  prva_prijava INTEGER NOT NULL,
  PRIMARY KEY (email)

);

CREATE TABLE MJESTO
(
  nazivMjesto VARCHAR NOT NULL,
  lat FLOAT NOT NULL,
  long FLOAT NOT NULL,
  PRIMARY KEY (nazivMjesto)
);

CREATE TABLE POTRES
(
  idPotres INT NOT NULL,
  intenzitet INT NOT NULL,
  magnituda FLOAT NOT NULL,
  nazivPotres VARCHAR NOT NULL,
  datum DATE NOT NULL,
  vrijeme TIME NOT NULL,
  novi INT CHECK (novi IN(0, 1)),
  PRIMARY KEY (idPotres)
);

CREATE TABLE UPITNIK
(
  idUpitnik INT NOT NULL,
  intenzitetUpitnik INT NOT NULL,
  datum DATE NOT NULL,
  vrijeme TIME NOT NULL,
  idPotres INT,
  nazivMjesto VARCHAR NOT NULL,
  PRIMARY KEY (idUpitnik),
  FOREIGN KEY (idPotres) REFERENCES POTRES(idPotres) ON DELETE CASCADE,
  FOREIGN KEY (nazivMjesto) REFERENCES MJESTO(nazivMjesto) ON DELETE CASCADE
);

CREATE TABLE ISPUNJENI_UPITNICI
(
  idUpitnik INT NOT NULL,
  idOdgovor INT NOT NULL,
  idPitanje INT NOT NULL,
  PRIMARY KEY (idUpitnik, idPitanje),
  FOREIGN KEY (idUpitnik) REFERENCES UPITNIK(idUpitnik) ON DELETE CASCADE,
  FOREIGN KEY (idOdgovor) REFERENCES ODGOVOR(idOdgovor) ON DELETE CASCADE,
  FOREIGN KEY (idPitanje) REFERENCES PITANJE(idPitanje) ON DELETE CASCADE
);
